pull_request_rules:
  - name: port patches to 3.1 branch
    conditions:
      - base=3.2.x
      - label=port-to-3.1
    actions:
      backport:
        branches:
          - 3.1.x
  - name: port patches to 3.2 branch
    conditions:
      - label=port-to-3.2
    actions:
      backport:
        branches:
          - 3.2.x
  - name: port patches to 3.3 branch
    conditions:
      - label=port-to-3.3
    actions:
      backport:
        branches:
          - 3.3.x
